---
apiVersion: wego.weave.works/v1alpha1
kind: Application
metadata:
  labels:
    weave-gitops.weave.works/app-identifier: wego-238d9b47a2ad5f0c8cf04b5acbd4663d
  name: podinfo-deploy
  namespace: wego-system
spec:
  branch: main
  deployment_type: kustomize
  path: ./
  source_type: git
  url: ssh://git@github.com/bconner22/podinfo-deploy.git
